Repository drop-the-beat-box/server, pull requests merged in 2023-06, with the labels that each got.

#37 feat FriendRestController PathVariable Vaildation 추가
  src/main/java/store/dropthebeatbox/app/exception/common/ErrorCode.java
  src/main/java/store/dropthebeatbox/app/repository/FriendRepository.java
  src/main/java/store/dropthebeatbox/app/validation/annotation/ExistFriend.java
  src/main/java/store/dropthebeatbox/app/validation/annotation/ExistFriendRequest.java
  src/main/java/store/dropthebeatbox/app/validation/annotation/ExistTeam.java
  src/main/java/store/dropthebeatbox/app/validation/validator/FriendExistValidator.java
  src/main/java/store/dropthebeatbox/app/validation/validator/FriendRequestValidator.java
  src/main/java/store/dropthebeatbox/app/validation/validator/TeamExistValidator.java
  src/main/java/store/dropthebeatbox/app/web/controller/FriendRestController.java
  src/main/java/store/dropthebeatbox/app/web/controller/TeamRestController.java
Labels: enhancement

#41 Issue/39 : 성훈 API 설명 추가하기
  src/main/java/store/dropthebeatbox/app/web/controller/FavoriteFileRestController.java
  src/main/java/store/dropthebeatbox/app/web/controller/FileRestController.java
  src/main/java/store/dropthebeatbox/app/web/controller/SharedFileRestController.java
Labels: documentation

#43 issue40 : 용욱 API 설명 추가하기
  src/main/java/store/dropthebeatbox/app/web/controller/FriendRestController.java
  src/main/java/store/dropthebeatbox/app/web/controller/MemberRestController.java
  src/main/java/store/dropthebeatbox/app/web/controller/TeamRestController.java
Labels: documentation

#46 issue45 : 친구 신청 API 수정
  src/main/java/store/dropthebeatbox/app/converter/FriendConverter.java
  src/main/java/store/dropthebeatbox/app/service/FriendService.java
  src/main/java/store/dropthebeatbox/app/service/impl/FriendServiceImpl.java
  src/main/java/store/dropthebeatbox/app/web/controller/FriendRestController.java
  src/main/java/store/dropthebeatbox/app/web/dto/FriendResponseDto.java
Labels: documentation, enhancement

#48 issue 47 : 멤버 검색 기능 구현
  src/main/java/store/dropthebeatbox/app/repository/MemberRepository.java
  src/main/java/store/dropthebeatbox/app/service/MemberService.java
  src/main/java/store/dropthebeatbox/app/service/impl/MemberServiceImpl.java
  src/main/java/store/dropthebeatbox/app/web/controller/MemberRestController.java
Labels: enhancement

#56 issue 49 : 팀에 멤버 초대 수정
  src/main/java/store/dropthebeatbox/app/converter/MemberConverter.java
  src/main/java/store/dropthebeatbox/app/repository/MemberRepository.java
  src/main/java/store/dropthebeatbox/app/service/MemberService.java
  src/main/java/store/dropthebeatbox/app/service/impl/MemberServiceImpl.java
  src/main/java/store/dropthebeatbox/app/web/controller/MemberRestController.java
  src/main/java/store/dropthebeatbox/app/web/dto/MemberRequestDto.java
  src/main/java/store/dropthebeatbox/app/web/dto/MemberResponseDto.java
Labels: enhancement

#58 issue57 : POST /team/{teamId}/member API 설명 추가, MemberRestController Validation 추가
  src/main/java/store/dropthebeatbox/app/web/controller/MemberRestController.java
Labels: documentation, enhancement

#64 issue63 : 멤버 조회시 json에 로그인 한 사용자와 친구인지 포함하기
  src/main/java/store/dropthebeatbox/app/converter/MemberConverter.java
  src/main/java/store/dropthebeatbox/app/repository/FriendRepository.java
  src/main/java/store/dropthebeatbox/app/web/controller/MemberRestController.java
  src/main/java/store/dropthebeatbox/app/web/dto/MemberResponseDto.java
Labels: enhancement

#70 issue/69 : PATCH Cors 허용
  src/main/java/store/dropthebeatbox/app/config/WebConfig.java
  src/main/resources/application.yml
Labels: bug

#71 issue 38 : SpringBatch 적용
  build.gradle
  src/main/java/store/dropthebeatbox/app/AppApplication.java
  src/main/java/store/dropthebeatbox/app/batch/BatchConfig.java
  src/main/java/store/dropthebeatbox/app/batch/SchedulingConfiguration.java
  src/main/java/store/dropthebeatbox/app/repository/FileRepository.java
  src/main/resources/application.yml
Labels: enhancement

#76 Issue/75 : ㅅ
  src/main/java/store/dropthebeatbox/app/converter/SharedFileConverter.java
  src/main/java/store/dropthebeatbox/app/domain/mapping/SharedFile.java
  src/main/java/store/dropthebeatbox/app/repository/MemberRepository.java
  src/main/java/store/dropthebeatbox/app/repository/SharedFileRepository.java
  src/main/java/store/dropthebeatbox/app/service/SharedFileService.java
  src/main/java/store/dropthebeatbox/app/service/impl/SharedFileServiceImpl.java
  src/main/java/store/dropthebeatbox/app/web/controller/SharedFileRestController.java
  src/main/java/store/dropthebeatbox/app/web/dto/SharedFileResponseDto.java
Labels: enhancement
